version: '3.8'

services:
  app:
    build:
      context: ../build
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../cmd/app:/app/cmd/app
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: filmoteka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abegah54
    ports:
      - "5432:5432"
